### ISSUE TITLE
ImportError: cannot import name 'RegexTokenizer'

### ISSUE THREAD

**Issue by marzique** [bureaucratic-labs/dostoevsky#39]
got this error when trying to run example code.
Even if I remove RegexTokenizer from import and set tokenizer = UDBaselineTokenizer() i have the following error: 

```
(vp36) Dannys-MBP:dost marzique$ python dost.py
Traceback (most recent call last):
  File "dost.py", line 2, in <module>
    from dostoevsky.embeddings import SocialNetworkEmbeddings
ModuleNotFoundError: No module named 'dostoevsky.embeddings'
```

please help

**Comment by dveselov** [comment]
Hi, since you're using version lower than latest, try examples [before the last release](https://github.com/bureaucratic-labs/dostoevsky/tree/c16f26c70b5c53231f935a95d7012a4a2f9f8501).

**Comment by marzique** [comment]
Thanks a lot!
It works, but for some reason almost all of my tested sentences predicted as neutral.
Even some like: 
```
вася убил брата.: neutral
сегодня хороший день.: positive
из бюджета было укражено 100000 рублей.: neutral

```

**Comment by dveselov** [comment]
I'm aware of this problem. As seen on confusion matrix (image below), almost 2/3 of sentences classified as neutral (maybe because dataset contains large amount of neutral cases, unbalanced..)  
I'm using this package for analytical purpose on large data, e.g. to get "average sentiment" of chat messages (check out difference on "Russian Python" community and "Rude Python" sentiment on Telegram)
![](https://camo.githubusercontent.com/f9614878bfc50825cb3862bdefe6bc06956f1d0a/68747470733a2f2f692e696d6775722e636f6d2f624741455776672e706e67)

**Comment by marzique** [comment]
> I'm aware of this problem. As seen on confusion matrix (image below), almost 2/3 of sentences classified as neutral (maybe because dataset contains large amount of neutral cases, unbalanced..)
> I'm using this package for analytical purpose on large data, e.g. to get "average sentiment" of chat messages (check out difference on "Russian Python" community and "Rude Python" sentiment on Telegram)
> ![](https://camo.githubusercontent.com/f9614878bfc50825cb3862bdefe6bc06956f1d0a/68747470733a2f2f692e696d6775722e636f6d2f624741455776672e706e67)

Got it.
Is there any beginner's friendly manual how to apply my own dataset to train the model?

**Comment by dveselov** [comment]
Currently, there is no manual on model training, sorry.
