### ISSUE TITLE
Model source code?

### ISSUE THREAD

**Issue by kuraga** [bureaucratic-labs/dostoevsky#88]
@dveselov , @annargrs, dataset has been removed due to Vk's request. But what about model's source code? After reading the article I thought it's available... Thanks!

**Comment by annargrs** [comment]
The model in Dostoyevsky library is entirely @dveselov's work, it is not what we experimented with in our paper.

**Comment by kuraga** [comment]
@annargrs, so it's question to you: does your paper have some published source code? Thanks!

**Comment by annargrs** [comment]
No, I don't think we published the baselines: they weren't anything fancy, and the main contribution was the data.

**Comment by kuraga** [comment]
Well, there' is "baselines source code are published" in article :) Thanks!

**Comment by kuraga** [comment]
@dveselov , so, this repository is _exactly_ "FastText model on RuSentiment dataset". Right?

**Comment by annargrs** [comment]
@kuraga Oops, our bad :) I'll see if anything can be excavated.

**Comment by kuraga** [comment]
@dveselov , if yes, is it correct: parameters of the model (removed but are correct instead) are in 5779ba089f43488058f470544028e579d703a503?

**Comment by annargrs** [comment]
@kuraga Nope, we did publish this repo 2 years ago, and it's linked from the project page: 
https://github.com/text-machine-lab/rusentiment_baselines

**Comment by kuraga** [comment]
@annargrs , thanks!

**Comment by dveselov** [comment]
> so, this repository is exactly "FastText model on RuSentiment dataset".

In this package I want to collect some good baselines for sentiment analysys task (since there are no alternatives that easy-installable and ready-to-use), not especially trained on RuSentiment dataset. For example, there is also fasttext-based model trained on toxic comments dataset (contains two classes - toxic and normal) - https://github.com/bureaucratic-labs/dostoevsky/blob/master/dostoevsky/models.py#L96

> If yes, is it correct: parameters of the model (removed but are correct instead) are in 5779ba0?

Yes, it is parameters I've used for training. They were obtained by [fasttext autotune](https://fasttext.cc/docs/en/autotune.html)

**Comment by kuraga** [comment]
Thanks!
